Add support to send logstash events to multiple endpoints
sensu-plugins/sensu-plugins-logstash pull request #16
Opened 2017-01-10 16:32 UTC by Evesy

## Pull Request Checklist

**Is this in reference to an existing issue?**
No

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
There is a need to send Logstash events to more than one endpoint, this change will allow you to specify several different endpoints (Address, host, output type), all of which will be looped through and the event sent.

This is an alternative, hopefully more lightweight, method to having multiple logstash handlers running for every event, which could become quite resource intensive.

#### Known Compatablity Issues
Breaking change.
The Logstash json will need to be updated in conjuction with this handler, else the handler will fail to run.

2017-01-12 14:02 UTC, sstarcher commented
This is a breaking change we will have to bump the version number.

2017-01-18 17:50 UTC, Evesy commented
@sstarcher Absolutely -- Would you be happy with the changes functionality wise?

2017-01-21 16:33 UTC, sstarcher commented
I'm fine with the changes.  Can you bump the version number.

2017-05-29 04:25 UTC, majormoses requested changes

2017-05-29 04:25 UTC, majormoses commented on CHANGELOG.md
> +## [1.0.0] - 2017-01-23
Remove version we will bump this, we will do this when we are ready to release.

2017-05-29 04:25 UTC, majormoses commented on lib/sensu-plugins-logstash/version.rb
> +    MAJOR = 1
remove version, see previous comment.

2017-05-29 04:25 UTC, majormoses commented on lib/sensu-plugins-logstash/version.rb
> +    MINOR = 0
remove version, see previous comment about version bumping.

2017-05-29 12:20 UTC, closed without merging